In [124]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [125]:
train = pd.read_csv('/content/drive/My Drive/Hackathon/Janatahack Machine Learning in Agriculture/train_yaOffsB.csv')
test = pd.read_csv('/content/drive/My Drive/Hackathon/Janatahack Machine Learning in Agriculture/test_pFkWwen.csv')
sub = pd.read_csv('/content/drive/My Drive/Hackathon/Janatahack Machine Learning in Agriculture/sample_submission_O1oDc4H.csv')

In [126]:
train.head()

ID  Estimated_Insects_Count  ...  Season  Crop_Damage
0  F00000001                      188  ...       1            0
1  F00000003                      209  ...       2            1
2  F00000004                      257  ...       2            1
3  F00000005                      257  ...       2            1
4  F00000006                      342  ...       2            1

[5 rows x 10 columns]

In [127]:
test.head()

ID  Estimated_Insects_Count  ...  Number_Weeks_Quit  Season
0  F00000002                      188  ...                  0       2
1  F00000007                      410  ...                  0       2
2  F00000011                      626  ...                  0       2
3  F00000013                      731  ...                  0       2
4  F00000014                      789  ...                  0       1

[5 rows x 9 columns]

In [128]:
sub.head()

ID  Crop_Damage
0  F00000002            1
1  F00000011            1
2  F00000014            1
3  F00000015            1
4  F00000016            1

In [129]:
train.isnull().sum()

ID                            0
Estimated_Insects_Count       0
Crop_Type                     0
Soil_Type                     0
Pesticide_Use_Category        0
Number_Doses_Week             0
Number_Weeks_Used          9000
Number_Weeks_Quit             0
Season                        0
Crop_Damage                   0
dtype: int64

In [130]:
train.shape, test.shape, sub.shape

((88858, 10), (59310, 9), (59310, 2))

In [131]:
train.columns

Index(['ID', 'Estimated_Insects_Count', 'Crop_Type', 'Soil_Type',
       'Pesticide_Use_Category', 'Number_Doses_Week', 'Number_Weeks_Used',
       'Number_Weeks_Quit', 'Season', 'Crop_Damage'],
      dtype='object')

In [132]:
cols = ['ID', 'Estimated_Insects_Count', 'Crop_Type', 'Soil_Type','Pesticide_Use_Category', 'Number_Doses_Week', 'Number_Weeks_Used',
        'Number_Weeks_Quit', 'Season', 'Crop_Damage']
for i in cols:  
  s = train[i].nunique()
  print('Number of Unique categories for', i,':\n',s)

Number of Unique categories for ID :
 88858
Number of Unique categories for Estimated_Insects_Count :
 71
Number of Unique categories for Crop_Type :
 2
Number of Unique categories for Soil_Type :
 2
Number of Unique categories for Pesticide_Use_Category :
 3
Number of Unique categories for Number_Doses_Week :
 20
Number of Unique categories for Number_Weeks_Used :
 64
Number of Unique categories for Number_Weeks_Quit :
 51
Number of Unique categories for Season :
 3
Number of Unique categories for Crop_Damage :
 3


In [133]:
del train['ID']
del test['ID']

In [134]:
train.head()

Estimated_Insects_Count  Crop_Type  ...  Season  Crop_Damage
0                      188          1  ...       1            0
1                      209          1  ...       2            1
2                      257          1  ...       2            1
3                      257          1  ...       2            1
4                      342          1  ...       2            1

[5 rows x 9 columns]

In [135]:
train['Crop_Damage'].value_counts()

0    74238
1    12307
2     2313
Name: Crop_Damage, dtype: int64

In [136]:
train.fillna(0,inplace=True)
test.fillna(0,inplace=True)

In [138]:
train['Number_Weeks_Used'] = train['Number_Weeks_Used'].astype(int)
test['Number_Weeks_Used'] = test['Number_Weeks_Used'].astype(int)

In [15]:
#import tensorflow as tf
#y = tf.keras.utils.to_categorical(y, num_classes=3)

In [139]:
X = train.loc[:, train.columns != 'Crop_Damage']
y = train['Crop_Damage']

In [140]:
y.nunique()

3

In [141]:
y.unique()

array([0, 1, 2])

In [142]:
y

0        0
1        1
2        1
3        1
4        1
        ..
88853    0
88854    0
88855    0
88856    0
88857    0
Name: Crop_Damage, Length: 88858, dtype: int64

In [143]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=12)

#TYPE I :

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
classifier = RandomForestClassifier(class_weight='balanced')
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight='balanced',
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
#classifier.fit(X_test,y_test)

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
print(pd.crosstab(y_test, y_pred, rownames=['Actual Crop_Damage'], colnames=['Crop_Damage']))

Crop_Damage             0    1    2
Actual Crop_Damage                 
0                   21235  973  145
1                    2756  722  150
2                     443  187   47


In [147]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))
print(accuracy_score(y_test, pred))

[[21924   429     0]
 [ 2940   683     5]
 [  470   206     1]]
              precision    recall  f1-score   support

           0       0.87      0.98      0.92     22353
           1       0.52      0.19      0.28      3628
           2       0.17      0.00      0.00       677

    accuracy                           0.85     26658
   macro avg       0.52      0.39      0.40     26658
weighted avg       0.80      0.85      0.81     26658

0.8480756245779878


In [ ]:
preds_rf = classifier.predict(test)

In [ ]:
test.isnull().sum()

Estimated_Insects_Count    0
Crop_Type                  0
Soil_Type                  0
Pesticide_Use_Category     0
Number_Doses_Week          0
Number_Weeks_Used          0
Number_Weeks_Quit          0
Season                     0
dtype: int64

In [65]:
test1 = pd.read_csv('/content/drive/My Drive/Hackathon/Janatahack Machine Learning in Agriculture/test_pFkWwen.csv')

In [151]:
df = {'ID':test1['ID'], 'Crop_Damage':pred_rf}

submit = pd.DataFrame(df)

In [152]:
submit['Crop_Damage'].nunique()

3

In [153]:
submit

ID  Crop_Damage
0      F00000002            1
1      F00000007            1
2      F00000011            1
3      F00000013            1
4      F00000014            1
...          ...          ...
59305  F00155937            0
59306  F00155940            0
59307  F00155941            0
59308  F00155943            0
59309  F00155944            0

[59310 rows x 2 columns]

In [154]:
pred_rf

array([1, 1, 1, ..., 0, 0, 0])

In [155]:
submit.to_csv('submissionagrf.csv',index=False)

In [21]:
import xgboost as xgb
from xgboost import XGBClassifier

In [69]:
classifier = XGBClassifier(objective='multi:softmax', num_classes=3) #n_estimators=1000 max_depth=5

In [70]:
classifier.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, num_classes=3, objective='multi:softprob',
              random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
              seed=None, silent=None, subsample=1, verbosity=1)

In [71]:
pred = classifier.predict(X_test)

In [72]:
pred_xgb = classifier.predict(test)

In [ ]:
######With some parameters changed

In [144]:
xg_class = XGBClassifier(objective = "multi:softmax", colsample_bytree = 1,
                         gamma = 1,subsample = 0.8, learning_rate = 0.1, max_depth = 3,
                         alpha = 10,n_estimators = 1000, num_classes = 3)

In [145]:
xg_class.fit(X_train,y_train)

XGBClassifier(alpha=10, base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=1,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=1000, n_jobs=1,
              nthread=None, num_classes=3, objective='multi:softprob',
              random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
              seed=None, silent=None, subsample=0.8, verbosity=1)

In [146]:
pred = xg_class.predict(X_test)

In [148]:
pred_rf = xg_class.predict(test)

In [ ]:
df = {'ID':test1['ID'], 'Crop_Damage':pred_rf}

In [ ]:
submit = pd.DataFrame(df)

In [ ]:
pred

In [ ]:
submit.to_csv('submissionagxgb.csv',index=False)